version: '3.7'

services:
  mysql_80:
    container_name: snippet_mysql_80
    image: mysql:8
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - snippet-mysql-data:/var/lib/mysql
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  snippet-mysql-data:
